version: '3.7'
services:  
  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./data:/data/db

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    command: python main.py
    tty: true
    ports:
      - "80:80"
    volumes:
      - ./backend:/app/:cached
      - ./.docker/.ipython:/root/.ipython:cached
    environment:
      PYTHONPATH: .
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - "mongodb"


